### PR TITLE
Support ghc 9.12

### PR DESCRIPTION
**Pull request by erikd**
Needed a `cabal.project` file containing the following to make it compile:

```
packages:
  .

tests: True

if impl (ghc >= 9.12)
  allow-newer:
    , hashable:base
    , integer-logarithms:base
    , integer-logarithms:ghc-prim
    , microlens-th:template-haskell
    , scientific:base
    , scientific:template-haskell
    , splitmix:base
    , time:template-haskell
    , unordered-containers:hashable
    , unordered-containers:template-haskell
```

### CODE REVIEW

**Comment by erikd** [comment]
> Thank you! Any idea why the first CI build failed?

I think its transient. I have touch the top commit and force pushed.

**Comment by erikd** [comment]
Damn, failed again. Its fails to find the required version of ghc (9.12.0.20241128) but I have updated a bunch of others like that and then were fine.

**Comment by jtdaugherty** [comment]
There are two entries that build with the same version of GHC (9.10.0.20241128), but one is failing and one isn't (or at least it didn't on the initial build). Do you know the difference between them? I am inclined to remove the one that's failing if the other one continues to work.

**Comment by erikd** [comment]
I have no idea why there are two. :confused:

**Comment by jtdaugherty** [comment]
Okay, thanks for this patch. I'll keep an eye on it and see about removing one if it's consistently failing for environment reasons.

**Comment by erikd** [comment]
Thanks @jtdaugherty . Would appreciate a Hackage metadata edit as well, unless you plan a new release in the near future.

**Comment by jtdaugherty** [comment]
@erikd I made a metadata update for 2.6.

**Pull request merged**
