### PR TITLE
Derive Functor instance for 'Next'

### PR DESCRIPTION
**Pull request by markus1189**
Missed that one recently and though adding it would be nice.

Btw, you did an awesome job with the `brick` redesign of `vty-ui` I am enjoying the `event-loop` + `pure state` very much :) :+1:

### CODE REVIEW

**Comment by jtdaugherty** [comment]
I kinda can't believe I missed `Functor` there, and `Applicative` needs to be added, too.  Thanks for your compliment! I'm glad you're getting a lot out of it. :)

**Comment by jtdaugherty** [comment]
(On second thought, `Applicative` might not be a good idea yet. `Halt` doesn't behave like you might expect so it would be possible to do things like `f <$> Halt s <*> Continue s2` and that would be bad.)

**Comment by jtdaugherty** [comment]
This change is now released: http://hackage.haskell.org/package/brick-0.6.4

**Comment by markus1189** [comment]
You have a really short time-to-market ;) Awesome :+1:

**Pull request merged**
