### PR TITLE
add instance MonadMask (EventM n)

### PR DESCRIPTION
**Pull request by frasertweedale**
I needed MonadMask instances for EventM in purebred in order to
generalise some functions.  I hope you will accept this PR so I
don't have carry orphan instances for too long :)

Let me know your feedback.  Cheers!

### CODE REVIEW

**Comment by frasertweedale** [comment]
CI glitch on the GHC 8.0 job:
```
$ sudo -E apt-add-repository -y "ppa:hvr/ghc"
Cannot add PPA: 'ppa:~hvr/ubuntu/ghc'.
The user named '~hvr' has no PPA named 'ubuntu/ghc'
Please choose from the following available PPAs:
 * 'cabal-staging':  Cabal (staging)
 * 'ghc':  GHC
 * 'ghc-boot':  GHC (bootstrap)
 * 'ghc-eoan':  GHC (eoan boostrap)
 * 'ghc-eol':  GHC (EOL)
 * 'ghc-staging':  GHC (staging)
 * 'ghc-wsl':  GHC (WSL)
 * 'ghcjs':  GHCJS
 * 'matrix.hackage':  Hackage CI
 * 'z3':  Z3
The command "sudo -E apt-add-repository -y "ppa:hvr/ghc"" failed and exited with 1 during .
```

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by frasertweedale** [comment]
Thanks @jtdaugherty :+1:

**Comment by jtdaugherty** [comment]
The changes in this PR are now released in `0.52`.

**Pull request merged**
