### PR TITLE
Edit: Bind M-< and M-> to gotoBOF and gotoEOF

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thank you!  Would you be willing to also update the `Editor` docs that mention the supported default keybindings?

**Comment by mlang** [comment]
done in a new commit on the same branch

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by jtdaugherty** [comment]
This change is now released in 0.64. Thanks again!

**Pull request merged**
