### PR TITLE
Add Giter

### PR DESCRIPTION
**Pull request by refaelsh**
Hi,

May I please add my new shiny project that uses Brick to the README?

Thanks.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Nice, thanks!

**Comment by jtdaugherty** [comment]
I suggest also adding a screenshot to your README - that will show off the application nicely!

**Comment by refaelsh** [comment]
> I suggest also adding a screenshot to your README - that will show off the application nicely!

Good idea. I will do it asap.

**Comment by refaelsh** [comment]
> > I suggest also adding a screenshot to your README - that will show off the application nicely!
> 
> Good idea. I will do it asap.

Done.

**Pull request merged**
