### PR TITLE
Bumped base version constraint to allow GHC 8.10

### PR DESCRIPTION
**Pull request by jchia**
#268

### CODE REVIEW

**Comment by jchia** [comment]
#268

**Comment by jtdaugherty** [comment]
Thank you! Would you be willing to also update the Travis config to build against 8.10?

**Comment by jchia** [comment]
Done. Not sure how to test my changes, though.

**Comment by jtdaugherty** [comment]
Travis is doing it for you: https://travis-ci.org/github/jtdaugherty/brick/jobs/678677760

Once that finishes green, I'll merge!

**Comment by martijnbastiaan** [comment]
@jtdaugherty Would you be willing to release a new version that includes this change, or relax the upper bounds of 0.52.1 on Hackage? :)

**Comment by jtdaugherty** [comment]
Done! http://hackage.haskell.org/package/brick-0.53

**Comment by martijnbastiaan** [comment]
Thank you!!

**Pull request merged**
