### PR TITLE
Use the generic module from text-zipper

### PR DESCRIPTION
**Pull request by dagit**
These changes go with my recent PR to text-zipper.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
This looks good, too. Can you bump the `text-zipper` dependency bound to `0.7`?

**Comment by dagit** [comment]
Please review again.

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by jtdaugherty** [comment]
It occurred to me that I can't push a release of this to Hackage until the User Guide has been updated since it mentions the editor shows its type / API.  If you have time to do that update, I can push a release of this today.  Otherwise it'll have to wait until perhaps Sunday.

**Pull request merged**
