### PR TITLE
Relax upper version bound for base to support GHC 8.6.1

### PR DESCRIPTION
**Pull request by maoe**
This requires https://github.com/aelve/microlens/pull/103 to be merged.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks. Presumably this will also require a `microlens` dependency bound bump in `brick` once the other patch is released.

**Comment by maoe** [comment]
A new version of microlens-th has been released.

**Comment by maoe** [comment]
Ping

**Comment by peti** [comment]
Ping?

**Comment by maoe** [comment]
I mean the upstream change has been merged andreleased on Hackage. Could we merge this? This is a blocking issue for adding GHC 8.6 support for my package.

**Comment by jtdaugherty** [comment]
@maoe Thanks for the reminder; I'll get to this in the next couple of days.

**Comment by peti** [comment]
Could at least please edit the version constraints on Hackage to fix the build of version 0.41.2? It compiles fine with ghc-8.6.x, so the constraint on `base <4.12` is definitely unnecessary.

**Comment by jtdaugherty** [comment]
I'm going to fix this, but for what it's worth, I haven't prioritized this because GHC 8.6 still has a serious codegen bug that has not yet been fixed (hence the release of 8.4.4 after the release of 8.6.1). So I strongly suggest you not use 8.6 until that has been resolved.

**Pull request merged**
