### PR TITLE
Fixed a few demos

### PR DESCRIPTION
**Pull request by njayinthehouse**
A few of the demos weren't compiling because of a little missing language extension declaration. All fixed!

Thanks for the great package! :)

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks for the patch. What version of Cabal and GHC was this on?

**Comment by njayinthehouse** [comment]
cabal-install version 1.24.0.2, and GHC version 8.0.2. Sorry for not specifying upfront, I'm a bit new to this.

**Comment by jtdaugherty** [comment]
Interesting - it must not be the GHC version, because on Travis, [Brick already builds on 8.0.2](https://travis-ci.org/jtdaugherty/brick/jobs/558098609
).

This language extension being missing has not been a problem on any of the Travis builds before. And I don't see anything in [the Cabal changelog](https://github.com/haskell/cabal/blob/master/cabal-install/changelog) about this behavior changing, either. So I'm confused about why this patch would be necessary.

**Comment by jtdaugherty** [comment]
Can you provide output from the build error that triggered this change?

**Comment by jtdaugherty** [comment]
I suspect the issue is that your version of cabal doesn't support `default-extensions`. The `CPP` extension is already provided in the `cabal` file for all the demos you needed to get building here, which explains why it works on Travis.

**Comment by jtdaugherty** [comment]
What version of the Cabal library is your `cabal` tool built with? I.e., what is the full output of `cabal --version`?

**Pull request closed without merging**
